server:
  port: 8882

spring:
  application:
#    name: config-client-colony
     name: config-client
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server-colony

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


