server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/i-Javan/iCloud/tree/master/iCloud/    # 配置git仓库的地址
          search-paths: respo                                           # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                                     # git仓库的账号
          password:                                                     # git仓库的密码